### ISSUE TITLE
MarketData WebSocket BookKeeper does not automatically restart upon receiving out of sequence messages.

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#3]
Upon receiving WebSocket messages out of sequence, Gemini's API docs instruct us to disconnect and reconnect, as a message has been missed.

With a friend's help, we received a message out of sequence on his network (possibly due to latency / network capabilities? has never been reproduced on my network). The command disconnected, as intended, but the error was not properly handled by the `Command` class and the command terminated rather than automatically reconnecting.

**Log:**
```
[2019-03-24T20:55:03.296553-05:00] btcusd.INFO: Opening "btcusd" on "api.sandbox.gemini.com" [] []
[2019-03-24T20:55:10.229193-05:00] btcusd.WARNING: {"symbol":"btcusd","errClass":"Kobens\\Gemini\\Exception\\Exception","errCode":0,"errMessage":"Out of sequence message"} [] []
[2019-03-24T20:55:10.229351-05:00] btcusd.WARNING: 
#0 /Users/green/www/vhosts/kobens-gemini/src/Api/WebSocket/MarketData/BookKeeper.php(61): Kobens\Gemini\Api\WebSocket\MarketData\BookKeeper->processMessage(Object(stdClass)) 
#1 [internal function]: Kobens\Gemini\Api\WebSocket\MarketData\BookKeeper->Kobens\Gemini\Api\WebSocket\MarketData\{closure}('a', NULL) 
#2 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Coroutine.php(76): Generator->send('{"type":"update...') 
#3 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Internal/Placeholder.php(130): Amp\Coroutine->Amp\{closure}(NULL, '{"type":"update...') 
#4 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Coroutine.php(81): Amp\Coroutine->resolve('{"type":"update...') 
#5 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Internal/Placeholder.php(130): Amp\Coroutine->Amp\{closure}(NULL, NULL) 
#6 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve(NULL) 
#7 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/byte-stream/lib/IteratorStream.php(57): Amp\Deferred->resolve() 
#8 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Success.php(36): Amp\ByteStream\IteratorStream->Amp\ByteStream\{closure}(NULL, false) 
#9 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Internal/Placeholder.php(125): Amp\Success->onResolve(Object(Closure)) 
#10 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve(Object(Amp\Success)) 
#11 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Internal/Producer.php(177): Amp\Deferred->resolve(Object(Amp\Success)) 
#12 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Emitter.php(57): class@anonymous->complete() 
#13 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/websocket/src/Rfc6455Client.php(355): Amp\Emitter->complete() 
#14 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/websocket/src/Rfc6455Client.php(942): Amp\Websocket\Rfc6455Client->onData(1, '{"type":"update...', true) 
#15 [internal function]: Amp\Websocket\Rfc6455Client->parser() 
#16 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/websocket/src/Rfc6455Client.php(277): Generator->send('\x81~\x00\xE6{"type":"up...') 
#17 [internal function]: Amp\Websocket\Rfc6455Client->read() 
#18 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Coroutine.php(76): Generator->send('\x81~\x00\xE6{"type":"up...') 
#19 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Internal/Placeholder.php(130): Amp\Coroutine->Amp\{closure}(NULL, '\x81~\x00\xE6{"type":"up...') 
#20 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve('\x81~\x00\xE6{"type":"up...') 
#21 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/byte-stream/lib/ResourceInputStream.php(99): Amp\Deferred->resolve('\x81~\x00\xE6{"type":"up...') 
#22 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Loop/NativeDriver.php(206): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('q', Resource id #300, NULL) 
#23 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Loop/NativeDriver.php(97): Amp\Loop\NativeDriver->selectStreams(Array, Array, 0.966) 
#24 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Loop/Driver.php(134): Amp\Loop\NativeDriver->dispatch(true) 
#25 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#26 /Users/green/www/vhosts/kobens-gemini/vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run() 
#27 /Users/green/www/vhosts/kobens-gemini/src/Api/WebSocket/MarketData/BookKeeper.php(39): Amp\Loop::run(Object(Closure)) #28 /Users/green/www/vhosts/kobens-gemini/src/Command/Command/Market/BookKeeper.php(73): Kobens\Gemini\Api\WebSocket\MarketData\BookKeeper->openBook()
#29 /Users/green/www/vhosts/kobens-gemini/vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\Market\BookKeeper->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /Users/green/www/vhosts/kobens-gemini/vendor/symfony/console/Application.php(909): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#31 /Users/green/www/vhosts/kobens-gemini/vendor/symfony/console/Application.php(270): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\Market\BookKeeper), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#32 /Users/green/www/vhosts/kobens-gemini/vendor/symfony/console/Application.php(146): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#33 /Users/green/www/vhosts/kobens-gemini/bin/gemini(44): Symfony\Component\Console\Application->run() 
#34 {main} [] []
```

**Todo:**
- [ ] Throw a more specific exception for this scenario, current class is `Kobens\Gemini\Exception\Exception`
- [ ] Catch exception and correctly re-connect 
- [ ] Track reconnect attempts that occur in a single thread, due to this exception. If it happens over an `X` threshold level, log this and abort further execution (no reason to keep reconnecting if we just keep receiving out of order messages all day long)
    - [ ] with above requirement, allow the `X` threshold to reset periodically (in other words, it's OK for a process healthily running all week long, to have this happen a couple times)
